# -*- coding: utf-8 -*-
"""E-Commerce Sales Analysis  mini pro1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kM-PbX9zHCJ1hdaffS9xs7nYgywCVJdH

# ** E-Commerce Sales analysis**
"""

from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt

uploaded=files.upload()

df=pd.read_csv("enterprise-customers-100.csv")

print(df)

df.head(10)

print(df.info())

print(df.shape)

df=df.drop_duplicates()

print(df)

print(df.isnull().sum())

total_sales=df['Contract Value'].sum()

print("total_sales:",total_sales)

product_sales=df.groupby('Industry')['Contract Value'].sum()

print(product_sales)

import pandas as pd
import matplotlib.pyplot as plt

# Re-loading the DataFrame here to ensure 'df' is defined in this cell's context.
df = pd.read_csv("enterprise-customers-100.csv")

product_sales = df.groupby('Industry')['Contract Value'].sum()

# Create the bar plot with a specified figure size for better readability
product_sales.plot(kind='bar', figsize=(15, 8))

plt.title('Product Sales Analysis')
plt.xlabel('Industry')
plt.ylabel('Total Sales')
plt.tight_layout() # Adjust layout to prevent labels from overlapping
plt.show()